#!/usr/bin/env node
// Writes js/daily.js: one puzzle a day for the next DAYS days, the same for
// everyone. Difficulty rises through the week, like a newspaper crossword:
// Monday gentle, Sunday fiendish.
//
// Easier puzzles come from random layouts (a position exactly the wanted
// number of moves from a solution). Harder ones come from a pool made by
// tools/search.js with a low threshold, for example:
//   node tools/search.js 300 77 18 /tmp/daily-pool.txt
// Every puzzle is checked with the game's solver, and none repeats a level
// or another day.
//
// Usage: node tools/daily.js <pool file> [first day, default 2026-09-28]
'use strict';

const fs = require('fs');
const path = require('path');
const Solver = require('../js/solver.js');
const { rng, randomLayout, distances, relabel } = require('./generate.js');

const DAYS = 730;
// Fewest moves by weekday (0 is Sunday).
const RANGES = { 1: [8, 10], 2: [11, 13], 3: [14, 17], 4: [18, 21], 5: [22, 25], 6: [26, 29], 0: [30, 34] };
const FROM_POOL = 18; // targets this hard or harder come from the pool
const OUT_FILE = path.join(__dirname, '..', 'js', 'daily.js');

function shuffle(list, rand) {
  for (let i = list.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    [list[i], list[j]] = [list[j], list[i]];
  }
  return list;
}

function main() {
  const [poolFile, start = '2026-09-28'] = process.argv.slice(2);
  if (!poolFile) throw new Error('Usage: node tools/daily.js <pool file> [first day]');
  const rand = rng(20260928);

  global.window = {};
  require('../js/levels.js');
  const used = new Set(window.GRIDLOCK_LEVELS.map((l) => l.board));

  // Pool boards by moves, shuffled so neighbouring days don't come from one climb.
  const pool = {};
  for (const line of fs.readFileSync(poolFile, 'utf8').split('\n')) {
    const [moves, , , board] = line.trim().split(/\s+/);
    if (board) (pool[moves] = pool[moves] || []).push(board);
  }
  for (const list of Object.values(pool)) shuffle(list, rand);

  const fromPool = (t) => {
    const list = pool[t] || [];
    while (list.length) {
      const board = list.pop();
      if (!used.has(board)) return board;
    }
    return null;
  };
  const fromRandom = (t) => {
    for (let tries = 0; tries < 50000; tries++) {
      const { vehicles, pos } = Solver.parse(randomLayout(rand));
      const result = distances(vehicles, pos);
      if (!result) continue;
      const at = [];
      for (const [k, d] of result.dist) if (d === t) at.push(k);
      if (!at.length) continue;
      const board = relabel(Solver.stringify(vehicles, result.seen.get(at[Math.floor(rand() * at.length)])));
      if (!used.has(board)) return board;
    }
    return null;
  };

  const first = new Date(start + 'T00:00:00Z');
  const puzzles = [];
  for (let i = 0; i < DAYS; i++) {
    const [lo, hi] = RANGES[(first.getUTCDay() + i) % 7];
    // A random number of moves in the day's range; if none is left at that
    // number, any other in the range will do.
    const options = shuffle(Array.from({ length: hi - lo + 1 }, (_, k) => lo + k), rand);
    let board = null;
    let t;
    for (t of options) {
      board = t >= FROM_POOL ? fromPool(t) : fromRandom(t);
      if (board) break;
    }
    if (!board) throw new Error(`Ran out of ${lo}-${hi} move puzzles on day ${i}; run a longer search`);
    const p = Solver.parse(board);
    const moves = Solver.solve(p.vehicles, p.pos).length;
    if (moves !== t) throw new Error(`Minimum moves mismatch for ${board}: ${moves} vs ${t}`);
    used.add(board);
    puzzles.push([board, t]);
  }

  const out =
    '// Generated by tools/daily.js. Do not edit by hand.\n' +
    '// One puzzle a day from `start`, as [board, fewest moves]; after the last they repeat.\n' +
    'window.GRIDLOCK_DAILY = {\n' +
    `  start: '${start}',\n` +
    '  puzzles: [\n' +
    puzzles.map(([b, m]) => `    ['${b}', ${m}],`).join('\n') +
    '\n  ],\n};\n';
  fs.writeFileSync(OUT_FILE, out);
  console.log(`Wrote ${puzzles.length} daily puzzles from ${start}`);
}

main();
